services:
  - type: web
    name: telegram-doc-pdf-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: "YOUR_TELEGRAM_BOT_TOKEN"
      - key: WEBHOOK_URL
        value: "YOUR_RENDER_URL/webhook"
